sync_config:
  branch: null
  email: mstseng@iastate.edu
  remote_repo_link: git@github.com:MattanTseng/Mage_Hackathon_2023.git
  repo_path: null
  ssh_private_key_secret_name: mage_git_ssh_private_key_b64
  ssh_public_key_secret_name: mage_git_ssh_public_key_b64
  sync_on_pipeline_run: null
  type: null
  username: MattanTseng
