sync_config:
  branch: null
  email: conrady.roselynn@gmail.com
  remote_repo_link: https://github.com/MattanTseng/Mage_Hackathon_2023.git
  repo_path: C:\Users\Roselynn Conrady\Documents\GitHub\Mage_Hackathon_2023
  ssh_private_key_secret_name: mage_git_ssh_private_key_b64
  ssh_public_key_secret_name: mage_git_ssh_public_key_b64
  sync_on_pipeline_run: false
  type: null
  username: rho-selynn
